#!/bin/bash
# Backup and tweak sources.list
cp /etc/apt/sources.list /etc/apt/sources.list.postinstall.bak
grep ^deb /etc/apt/sources.list.postinstall.bak | sed 's/buster main\$/buster main contrib non-free/g' > /etc/apt/sources.list
# sed -i 's/buster main\$/buster main contrib non-free/g' /etc/apt/sources.list

# Remove obsolete base.list
rm -f /etc/apt/sources.list.d/base.list

